# Generated by Django 4.2.1 on 2023-05-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_employee",
            field=models.BooleanField(default=True, verbose_name="Is employee"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_employer",
            field=models.BooleanField(default=True, verbose_name="Is employer"),
        ),
    ]
