# Generated by Django 4.2.1 on 2023-05-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_course_room_resource_message_announcement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="start_date",
            new_name="created",
        ),
        migrations.RemoveField(
            model_name="course",
            name="end_date",
        ),
        migrations.AddField(
            model_name="course",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
