# Generated by Django 4.2.1 on 2023-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_course_room_resource_message_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="youtubeLink",
            field=models.TextField(blank=True),
        ),
    ]
