# Generated by Django 4.2.1 on 2023-05-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_resource_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
