# Generated by Django 4.2.1 on 2023-05-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_announcement_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="room_host",
        ),
    ]
