# Generated by Django 4.2.1 on 2023-05-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_room_room_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
