# Generated by Django 4.2.1 on 2023-05-18 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_room_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="resource",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
