# Generated by Django 4.2.1 on 2023-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_resource_created_resource_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
