# Generated by Django 4.2.1 on 2023-05-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_resource_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
