# Generated by Django 4.2.1 on 2023-05-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_alter_resource_description_alter_resource_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message_host",
            new_name="user",
        ),
    ]
