# Generated by Django 4.2.1 on 2023-05-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_room_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="participants",
        ),
    ]
