# Generated by Django 4.2.1 on 2023-05-21 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_remove_course_course_participants_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participants",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="enrollments", to="myapp.participants"
            ),
        ),
    ]
