# Generated by Django 4.2.1 on 2023-05-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_alter_participants_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.RemoveField(
            model_name="participants",
            name="course",
        ),
        migrations.RemoveField(
            model_name="participants",
            name="user",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="course",
        ),
        migrations.RemoveField(
            model_name="room",
            name="course",
        ),
        migrations.DeleteModel(
            name="Announcement",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Participants",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
