from django.shortcuts import render, redirect
from course.models import Course, Room, Message

def chatRoom(request, pk2, pk):
    """
    Render the employee chat room page for a specific room.

    This view function retrieves the necessary data to display the chat room page for a specific room in a course.
    It fetches the courses in which the employee is a participant, retrieves the specific course and room based on
    the provided primary keys (pk2 and pk), and fetches all messages associated with the room.

    If the HTTP request method is POST, a new message is created and associated with the room. The page is then
    redirected back to the chat room with the updated message.

    Parameters:
    - request: The HTTP request object generated by the user's interaction with the web application.
    - pk2: The primary key of the course to which the chat room belongs.
    - pk: The primary key of the chat room being accessed.

    Returns:
    - If the request method is POST, the function redirects to the chat room page with the updated message.
    - Otherwise, it renders the chat room template with the necessary context data.

    """

    # Retrieve the currently logged-in employee
    employee = request.user

    # Get all courses in which the employee is a participant
    courses = Course.objects.filter(participants__user=employee)

    # Retrieve the course based on the provided primary key
    course = Course.objects.get(id=pk2)

    # Retrieve the room based on the provided primary key
    room = Room.objects.get(id=pk)

    # Retrieve all messages associated with the room, ordered by creation time
    room_messages = room.message_set.all().order_by('-created')

    if request.method == 'POST':
        # Create a new message associated with the room
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        return redirect('chat-room', pk2=course.id, pk=room.id)

    context = {
        'room': room,
        'room_messages': room_messages,
        'courses': courses,
        'course': course,
        'page': 'chat-room'
    }

    # Render the chat room template with the context data
    return render(request, "chat/chat_room.html", context)
