from django.shortcuts import render, redirect
from course.models import Course, Room, Message, VideoStreamMember
from django.http import JsonResponse
from agora_token_builder import RtcTokenBuilder
from django.conf import settings
import random
import time
import json
from django.views.decorators.csrf import csrf_exempt

def chatRoom(request, pk2, pk):
    """
    Render the employee chat room page for a specific room.

    This view function retrieves the necessary data to display the chat room page for a specific room in a course.
    It fetches the courses in which the employee is a participant, retrieves the specific course and room based on
    the provided primary keys (pk2 and pk), and fetches all messages associated with the room.

    If the HTTP request method is POST, a new message is created and associated with the room. The page is then
    redirected back to the chat room with the updated message.

    Parameters:
    - request: The HTTP request object generated by the user's interaction with the web application.
    - pk2: The primary key of the course to which the chat room belongs.
    - pk: The primary key of the chat room being accessed.

    Returns:
    - If the request method is POST, the function redirects to the chat room page with the updated message.
    - Otherwise, it renders the chat room template with the necessary context data.

    """

    # Retrieve the currently logged-in employee
    employee = request.user

    # Get all courses in which the employee is a participant
    courses = Course.objects.filter(participants__user=employee)

    # Retrieve the course based on the provided primary key
    course = Course.objects.get(id=pk2)

    # Retrieve the room based on the provided primary key
    room = Room.objects.get(id=pk)

    # Retrieve all messages associated with the room, ordered by creation time
    room_messages = room.message_set.all().order_by('-created')

    if request.method == 'POST':
        # Create a new message associated with the room
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        return redirect('chat-room', pk2=course.id, pk=room.id)

    context = {
        'room': room,
        'room_messages': room_messages,
        'courses': courses,
        'course': course,
        'page': 'chat-room'
    }

    # Render the chat room template with the context data
    return render(request, "chat/chat_room.html", context)


def videoStream(request, pk):
    channel_name = Room.objects.get(id=pk)
    context = {'channel_name':channel_name}
    return render(request, "chat/video_stream.html", context)


def getToken(request):
    appId = settings.APP_ID
    appCertificate = settings.APP_CERTIFICATE
    channelName = request.GET.get('channel')
    uid = random.randint(1, 230)
    expirationTimeInSeconds = 3600
    currentTimeStamp = int(time.time())
    privilegeExpiredTs = currentTimeStamp + expirationTimeInSeconds
    role = 1

    token = RtcTokenBuilder.buildTokenWithUid(appId, appCertificate, channelName, uid, role, privilegeExpiredTs)

    return JsonResponse({'token': token, 'uid': uid}, safe=False)


@csrf_exempt
def createMember(request):
    data = json.loads(request.body)
    member, created = VideoStreamMember.objects.get_or_create(
        name=data['name'],
        uid=data['UID'],
        room_name=data['room_name']
    )

    return JsonResponse({'name':data['name']}, safe=False)


def getMember(request):
    uid = request.GET.get('UID')
    room_name = request.GET.get('room_name')

    member = VideoStreamMember.objects.get(
        uid=uid,
        room_name=room_name,
    )
    name = member.name
    return JsonResponse({'name':member.name}, safe=False)

@csrf_exempt
def deleteMember(request):
    data = json.loads(request.body)
    member = VideoStreamMember.objects.get(
        name=data['name'],
        uid=data['UID'],
        room_name=data['room_name']
    )
    member.delete()
    return JsonResponse('Member deleted', safe=False)

